// AUTO-GENERATED by scripts/build-indexes.py - do not edit by hand.
// Edit the individual files under indexes/ instead, then re-run that script.

// ---- indexes/Textures/Items/dress02_i.js ----
GERSANG_LABELS["dress02_i.AGF"] = {
    name: "의복2",
    items: {
        "22": "복희의 의복",
        "23": "츠쿠요미 의복"
    }
};
GERSANG_LABELS["dress02_i.AGF"].folder = "Textures/Items";

