// AUTO-GENERATED by scripts/build-indexes.py - do not edit by hand.
// Edit the individual files under indexes/ instead, then re-run that script.

// ---- indexes/Textures/Items/archeology01_i.js ----
GERSANG_LABELS["archeology01_i.AGF"] = {
    name: "고고학",
    items: {
        
    }
};
GERSANG_LABELS["archeology01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor01_i.js ----
GERSANG_LABELS["armor01_i.AGF"] = {
    name: "갑옷",
    items: {
        
    }
};
GERSANG_LABELS["armor01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor02_i.js ----
GERSANG_LABELS["armor02_i.AGF"] = {
    name: "방어구 및 반지",
    items: {
        
    }
};
GERSANG_LABELS["armor02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor03_i.js ----
GERSANG_LABELS["armor03_i.AGF"] = {
    name: "갑옷 및 투구",
    items: {
        
    }
};
GERSANG_LABELS["armor03_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor04_i.js ----
GERSANG_LABELS["armor04_i.AGF"] = {
    name: "방어구 및 반지",
    items: {
        
    }
};
GERSANG_LABELS["armor04_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor05_i.js ----
GERSANG_LABELS["armor05_i.AGF"] = {
    name: "방어구",
    items: {
        
    }
};
GERSANG_LABELS["armor05_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/armor06_i.js ----
GERSANG_LABELS["armor06_i.AGF"] = {
    name: "방어구 및 장신구",
    items: {
        
    }
};
GERSANG_LABELS["armor06_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/belt01_i.js ----
GERSANG_LABELS["belt01_i.AGF"] = {
    name: "요대",
    items: {
        
    }
};
GERSANG_LABELS["belt01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/cashmall.js ----
GERSANG_LABELS["cashmall.AGF"] = {
    name: "캐시템",
    items: {
        
    }
};
GERSANG_LABELS["cashmall.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/creature01_i.js ----
GERSANG_LABELS["creature01_i.AGF"] = {
    name: "사천왕 재료",
    items: {
        
    }
};
GERSANG_LABELS["creature01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/creature_i.js ----
GERSANG_LABELS["creature_i.AGF"] = {
    name: "신수 재료",
    items: {
        
    }
};
GERSANG_LABELS["creature_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/doll01_i.js ----
GERSANG_LABELS["doll01_i.AGF"] = {
    name: "무기 - 인형",
    items: {
        
    }
};
GERSANG_LABELS["doll01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/dress01_i.js ----
GERSANG_LABELS["dress01_i.AGF"] = {
    name: "의복",
    items: {
        
    }
};
GERSANG_LABELS["dress01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/dress02_i.js ----
GERSANG_LABELS["dress02_i.AGF"] = {
    name: "의복",
    items: {
        "22": "복희의 의복",
        "23": "츠쿠요미 의복"
    }
};
GERSANG_LABELS["dress02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element01_i.js ----
GERSANG_LABELS["element01_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element02_i.js ----
GERSANG_LABELS["element02_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element03_i.js ----
GERSANG_LABELS["element03_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element03_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element04_i.js ----
GERSANG_LABELS["element04_i.AGF"] = {
    name: "재료 및 천왕부",
    items: {
        
    }
};
GERSANG_LABELS["element04_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element05_i.js ----
GERSANG_LABELS["element05_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element05_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element06_i.js ----
GERSANG_LABELS["element06_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element06_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element07_i.js ----
GERSANG_LABELS["element07_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element07_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element08_i.js ----
GERSANG_LABELS["element08_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element08_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element09_i.js ----
GERSANG_LABELS["element09_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element09_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element10_i.js ----
GERSANG_LABELS["element10_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element10_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element11_i.js ----
GERSANG_LABELS["element11_i.AGF"] = {
    name: "재료 및 명왕부",
    items: {
        
    }
};
GERSANG_LABELS["element11_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element12_i.js ----
GERSANG_LABELS["element12_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element12_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element13_i.js ----
GERSANG_LABELS["element13_i.AGF"] = {
    name: "재료 및 명왕부",
    items: {
        
    }
};
GERSANG_LABELS["element13_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element14_i.js ----
GERSANG_LABELS["element14_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element14_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element15_i.js ----
GERSANG_LABELS["element15_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element15_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element16_i.js ----
GERSANG_LABELS["element16_i.AGF"] = {
    name: "재료",
    items: {
        
    }
};
GERSANG_LABELS["element16_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/element_i.js ----
GERSANG_LABELS["element_i.AGF"] = {
    name: "화포 폭죽 드래곤볼",
    items: {
        
    }
};
GERSANG_LABELS["element_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/enchantrecipe_i.js ----
GERSANG_LABELS["enchantrecipe_i.AGF"] = {
    name: "주술 비법",
    items: {
        
    }
};
GERSANG_LABELS["enchantrecipe_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/food01_i.js ----
GERSANG_LABELS["food01_i.AGF"] = {
    name: "소모품 및 버프",
    items: {
        
    }
};
GERSANG_LABELS["food01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/food02_i.js ----
GERSANG_LABELS["food02_i.AGF"] = {
    name: "소모품 및 버프",
    items: {
        
    }
};
GERSANG_LABELS["food02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/food03_i.js ----
GERSANG_LABELS["food03_i.AGF"] = {
    name: "상자",
    items: {
        
    }
};
GERSANG_LABELS["food03_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/food04_i.js ----
GERSANG_LABELS["food04_i.AGF"] = {
    name: "소모품 및 버프",
    items: {
        
    }
};
GERSANG_LABELS["food04_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/glove01_i.js ----
GERSANG_LABELS["glove01_i.AGF"] = {
    name: "장갑",
    items: {
        
    }
};
GERSANG_LABELS["glove01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/helmet01_i.js ----
GERSANG_LABELS["helmet01_i.AGF"] = {
    name: "투구",
    items: {
        
    }
};
GERSANG_LABELS["helmet01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/helmet02_i.js ----
GERSANG_LABELS["helmet02_i.AGF"] = {
    name: "투구",
    items: {
        
    }
};
GERSANG_LABELS["helmet02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/lhwapo01_i.js ----
GERSANG_LABELS["lhwapo01_i.AGF"] = {
    name: "화포",
    items: {
        
    }
};
GERSANG_LABELS["lhwapo01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem001.js ----
GERSANG_LABELS["litem001.AGF"] = {
    name: "싸전 / 시전 템",
    items: {
        
    }
};
GERSANG_LABELS["litem001.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem002.js ----
GERSANG_LABELS["litem002.AGF"] = {
    name: "무기점 템",
    items: {
        
    }
};
GERSANG_LABELS["litem002.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem003.js ----
GERSANG_LABELS["litem003.AGF"] = {
    name: "무기 및 의복",
    items: {
        
    }
};
GERSANG_LABELS["litem003.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem004.js ----
GERSANG_LABELS["litem004.AGF"] = {
    name: "시전 / 무기점 / 싸전 템",
    items: {
        
    }
};
GERSANG_LABELS["litem004.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem005.js ----
GERSANG_LABELS["litem005.AGF"] = {
    name: "시전 / 무기점 / 싸전 템",
    items: {
        
    }
};
GERSANG_LABELS["litem005.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem006.js ----
GERSANG_LABELS["litem006.AGF"] = {
    name: "시전 / 무기점 / 싸전 템",
    items: {
        
    }
};
GERSANG_LABELS["litem006.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem007.js ----
GERSANG_LABELS["litem007.AGF"] = {
    name: "시전 / 무기점 / 약방 템 / 신발 / 반지 / 장갑",
    items: {
        
    }
};
GERSANG_LABELS["litem007.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem008.js ----
GERSANG_LABELS["litem008.AGF"] = {
    name: "의복 / 갑옷",
    items: {
        
    }
};
GERSANG_LABELS["litem008.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem009.js ----
GERSANG_LABELS["litem009.AGF"] = {
    name: "투구/반지/무기/소모품/재료/천년호 템",
    items: {
        
    }
};
GERSANG_LABELS["litem009.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem010.js ----
GERSANG_LABELS["litem010.AGF"] = {
    name: "검/도끼/목탁/부채/팔찌/염주/원앙월/총/활",
    items: {
        
    }
};
GERSANG_LABELS["litem010.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem011.js ----
GERSANG_LABELS["litem011.AGF"] = {
    name: "봉/쌍검/요대/캐시템/의복",
    items: {
        
    }
};
GERSANG_LABELS["litem011.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem012.js ----
GERSANG_LABELS["litem012.AGF"] = {
    name: "장갑/검/활/목탁/도끼/재료/드랍템",
    items: {
        
    }
};
GERSANG_LABELS["litem012.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/litem013.js ----
GERSANG_LABELS["litem013.AGF"] = {
    name: "쿠크리/신수무기/지팡이/활/목탁/석궁/원반",
    items: {
        
    }
};
GERSANG_LABELS["litem013.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/lunique01.js ----
GERSANG_LABELS["lunique01.AGF"] = {
    name: "챠우신전 드랍템/퀘스트보상/챠우인형",
    items: {
        
    }
};
GERSANG_LABELS["lunique01.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/lunique02.js ----
GERSANG_LABELS["lunique02.AGF"] = {
    name: "캐시템",
    items: {
        
    }
};
GERSANG_LABELS["lunique02.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/mall01_i.js ----
GERSANG_LABELS["mall01_i.AGF"] = {
    name: "의복/무자/인형",
    items: {
        
    }
};
GERSANG_LABELS["mall01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/medic01_i.js ----
GERSANG_LABELS["medic01_i.AGF"] = {
    name: "약초",
    items: {
        
    }
};
GERSANG_LABELS["medic01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/ring01_i.js ----
GERSANG_LABELS["ring01_i.AGF"] = {
    name: "반지/목걸이/귀걸이",
    items: {
        
    }
};
GERSANG_LABELS["ring01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/ring02_i.js ----
GERSANG_LABELS["ring02_i.AGF"] = {
    name: "반지/목걸이/팔찌/각반",
    items: {
        
    }
};
GERSANG_LABELS["ring02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/ring03_i.js ----
GERSANG_LABELS["ring03_i.AGF"] = {
    name: "반지/목걸이/각반",
    items: {
        
    }
};
GERSANG_LABELS["ring03_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/rweapon01_i.js ----
GERSANG_LABELS["rweapon01_i.AGF"] = {
    name: "무기",
    items: {
        
    }
};
GERSANG_LABELS["rweapon01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/shoes01_i.js ----
GERSANG_LABELS["shoes01_i.AGF"] = {
    name: "신발",
    items: {
        
    }
};
GERSANG_LABELS["shoes01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/siege01_i.js ----
GERSANG_LABELS["siege01_i.AGF"] = {
    name: "공성 템",
    items: {
        
    }
};
GERSANG_LABELS["siege01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/soccerball_i.js ----
GERSANG_LABELS["soccerball_i.AGF"] = {
    name: "축구공/빛",
    items: {
        
    }
};
GERSANG_LABELS["soccerball_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/special01_i.js ----
GERSANG_LABELS["special01_i.AGF"] = {
    name: "수호부/신수부/폭죽/부적",
    items: {
        
    }
};
GERSANG_LABELS["special01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/star01_i_1.js ----
GERSANG_LABELS["star01_i_1.AGF"] = {
    name: "별자리",
    items: {
        
    }
};
GERSANG_LABELS["star01_i_1.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/treasurebox_i.js ----
GERSANG_LABELS["treasurebox_i.AGF"] = {
    name: "상자",
    items: {
        
    }
};
GERSANG_LABELS["treasurebox_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/u_f_cheonha_i.js ----
GERSANG_LABELS["u_f_cheonha_i.AGF"] = {
    name: "천하장사",
    items: {
        
    }
};
GERSANG_LABELS["u_f_cheonha_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/weapon01_i.js ----
GERSANG_LABELS["weapon01_i.AGF"] = {
    name: "천왕무기/인형",
    items: {
        
    }
};
GERSANG_LABELS["weapon01_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/weapon02_i.js ----
GERSANG_LABELS["weapon02_i.AGF"] = {
    name: "무기/인형",
    items: {
        
    }
};
GERSANG_LABELS["weapon02_i.AGF"].folder = "Textures/Items";

// ---- indexes/Textures/Items/wetc_i.js ----
GERSANG_LABELS["wetc_i.AGF"] = {
    name: "무기",
    items: {
        
    }
};
GERSANG_LABELS["wetc_i.AGF"].folder = "Textures/Items";

